export default {
    
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",
    FLUSH_POPULAR_FAVORITE: "FLUSH_POPULAR_FAVORITE",

    TRENDING_FLUSH_FAVORITE: "TRENDING_FLUSH_FAVORITE",
    TRENDING_REFRESH: "TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
    TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",
    TRENDING_FLUSH_FAVORITE: "TRENDING_FLUSH_FAVORITE",
    
    FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",

    LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS",

    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",

    SEARCH_LOAD_MORE_SUCCESS: "SEARCH_LOAD_MORE_SUCCESS",
    SEARCH_LOAD_MORE_FAIL: "SEARCH_LOAD_MORE_FAIL",
    SEARCH_REFRESH: "SEARCH_REFRESH",
    SEARCH_CANCEL: "SEARCH_CANCEL",
    SEARCH_FAIL: "SEARCH_FAIL",
    SEARCH_REFRESH_SUCCESS: "SEARCH_REFRESH_SUCCESS",

}