# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reduxNavTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCCommonLog'
    #  统计
    pod 'UMCAnalytics'
    #  分享和登陆
    pod 'UMCShare/UI'
    pod 'UMCShare/Social/ReducedWeChat'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
    pod 'UMCShare/Social/Email'
    pod 'UMCShare/Social/SMS'

end


